name: Flutter action
on: push
jobs:
  analyze:
    name: 'Run flutter analyzer'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
      - run: flutter pub get
      - run: flutter analyze
