name: Deploy to Github Pages
on: push
jobs:
  Build:
    name: 'Build and Deploy GH'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: 'Build web version'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
      - run: flutter build web --base-href "/prspy/"
      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build/web